<%@ Page Title="" Language="C#" MasterPageFile="~/PageMaster.Master" AutoEventWireup="true" CodeBehind="Listar.aspx.cs" Inherits="User_Manager.Listar" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>LISTAR USUARIOS</h1>
    <div>
        
        <div>
            <asp:Label ID="lblCodigo" runat="server" CssClass="form-label" Text="Codigo: "></asp:Label>
            <asp:TextBox ID="txtCodigo" runat="server" CssClass="form-control"></asp:TextBox>
        </div>

        <div>
            <asp:Label ID="lblApellido" runat="server" CssClass="form-label" Text="Apellidos: "></asp:Label>
            <asp:TextBox ID="txtApellido" runat="server" CssClass="form-control"></asp:TextBox>
        </div>

        <div>
            <asp:Label ID="lblGenero" runat="server" CssClass="form-label" Text="Genero: "></asp:Label>
            <asp:DropDownList ID="ddlGenero" runat="server" CssClass="form-select">
            <asp:ListItem Text="--Seleccionar--" Value=""></asp:ListItem>            
            </asp:DropDownList>
        </div>

        <div>
            <asp:Label ID="lblNacionalidad" runat="server" CssClass="form-label" Text="Nacionalidad: "></asp:Label>
            <asp:DropDownList ID="ddlNacionalidad" runat="server" CssClass="form-select">
            <asp:ListItem Text="--Seleccionar--" Value=""></asp:ListItem>
            </asp:DropDownList>
        </div>

        <div>
            <asp:Label ID="lblPerfil" runat="server" CssClass="form-label" Text="Perfil: "></asp:Label>
            <asp:DropDownList ID="ddlPerfil" runat="server" CssClass="form-select">
            <asp:ListItem Text="--Seleccionar--" Value=""></asp:ListItem>
            </asp:DropDownList>
        </div>

        <div>
            <asp:Button ID="btnBuscar" runat="server" CssClass="btn btn-primary" Text="Buscar" OnClick="btnBuscar_Click" />
        </div>
        
        <div>
            <asp:GridView ID="gvUsuario" runat="server" CssClass="table table-striped" AllowPaging="true" OnPageIndexChanging="gvUsuario_PageIndexChanging" AutoGenerateColumns="false" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" OnRowEditing="gvUsuario_RowEditing" OnRowDeleting="gvUsuario_RowDeleting">

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblId" Text="Id"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblId2" Text='<%# Eval("id") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblCodigo" Text="Codigo"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblCodigo2" Text='<%# Eval("codigo") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblNombre" Text="Nombres"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblNombre2" Text='<%# Eval("nombre") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblApellido" Text="Apellidos"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblApellido2" Text='<%# Eval("apellido") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblEdad" Text="Edad"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblEdad2" Text='<%# Eval("edad") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblGenero" Text="Genero"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblGenero2" Text='<%# Eval("idGenero") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblNacionalidad" Text="Nacionalidad"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblNacionalidad" Text='<%# Eval("idNacionalidad") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblPerfil" Text="Perfil"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblPerfil" Text='<%# Eval("idPerfil") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

            </asp:GridView>
        </div>


    </div>
</asp:Content>
